version: '2.3'

services:

## Logstash service
  logstash:
    build: .
    container_name: logstash
    restart: always
    env_file:
     # - /opt/tpot/etc/compose/elk_environment
     - ./dist/elk_environment
    image: "dtagdevsec/logstash:1903"
    volumes:
     - /data:/data
     # - /root/tpotce/docker/elk/logstash/dist/logstash.conf:/etc/logstash/conf.d/logstash.conf
     - ./dist/logstash.conf:/etc/logstash/conf.d/logstash.conf
